"""
Layer 13: Gemini AI Master Trader Verification Layer.

This module packages the raw technical context of a trade signal
and sends it to Google's Gemini LLM. The LLM acts as an expert
quantitative analyst and provides a final WIN/LOSE/UNCERTAIN verdict.
"""

import os
import logging
import json
import google.generativeai as genai
from config import GEMINI_API_KEY

log = logging.getLogger("gemini_filter")

# Initialize Gemini if an API key is provided
_gemini_enabled = False
if GEMINI_API_KEY:
    try:
        genai.configure(api_key=GEMINI_API_KEY)
        
        system_instruction = (
            "You are an expert quantitative trading analyst specializing in Fixed-Time (Binary Options) markets "
            "like Quotex and Pocket Option. Your horizon is strictly the IMMEDIATE NEXT 5-MINUTE CANDLE. "
            "Do not analyze macro-trends or multi-hour swing trades. "
            "Your task is to analyze a trading signal generated by an ML ensemble and determine if the "
            "IMMEDIATE NEXT 5-MINUTE CANDLE will close higher (WIN for BUY) or lower (WIN for SELL) than its open. "
            "Use your knowledge of technical analysis, market microstructure, candlestick patterns (dojis, wicks), "
            "and immediate volume imbalances to predict the 5-minute expiry outcome. Provide a verdict with "
            "reasoning and a confidence score. Output must be valid JSON only."
        )
        
        # Using gemini-2.5-flash with JSON mode
        _model = genai.GenerativeModel(
            model_name='gemini-2.5-flash',
            system_instruction=system_instruction,
            generation_config=genai.GenerationConfig(
                temperature=0.2,
                max_output_tokens=1024,
                response_mime_type="application/json"
            )
        )
        _gemini_enabled = True
        log.info("Gemini API Verification Layer ENABLED (Advanced Prop-Trader Prompt).")
    except Exception as e:
        log.warning("Failed to initialize Gemini API: %s", e)
else:
    log.warning("GEMINI_API_KEY not found in config. Layer 13 will be skipped.")

def verify_signal(
    symbol: str, 
    timestamp: str,
    direction: str,
    green_prob: float,
    confidence: float,
    meta_trust: float,
    uncertainty: float,
    regime: str,
    session: str,
    kelly: float,
    recent_candles: str,
    support1: str,
    resistance1: str,
    ema20: float,
    ema50: float,
    rsi: float,
    atr: float,
    news_sentiment: str = "N/A"
) -> dict:
    """
    Sends the structural trade context to Gemini for final verification.
    
    Returns:
        dict: {
            "approved": bool,
            "reason": str,
            "gemini_confidence": int,
            "verdict": str
        }
    """
    if not _gemini_enabled:
        return {"approved": True, "reason": "Gemini disabled (No API Key)", "gemini_confidence": 0, "verdict": "SKIPPED"}
    
    prompt = f"""Analyze the following trading signal and market context. Decide if the signal will likely WIN (price moves in the predicted direction), LOSE (price moves opposite), or if it's UNCERTAIN. Also suggest any adjustments to the probability or confidence.

Signal Details:
- Symbol: {symbol}
- Timestamp (UTC): {timestamp}
- Direction: {direction} (BUY=up, SELL=down)
- ML Probability (ensemble mean): {green_prob:.4f}
- Confidence (final blended score): {confidence:.2f}
- Meta Trust (reliability of primary model): {meta_trust:.2f}
- Ensemble Variance (uncertainty): {uncertainty:.4f}
- Market Regime: {regime}
- Session: {session}
- Kelly Size (%): {kelly:.2f}

Recent Market Data (last 5 completed M5 candles OHLCV):
{recent_candles}

Key Technical Levels (computed from higher timeframes):
- Support 1: {support1}
- Resistance 1: {resistance1}
- 20 EMA: {ema20:.5f}
- 50 EMA: {ema50:.5f}
- RSI(14): {rsi:.2f}
- ATR(14): {atr:.5f}

Recent News Sentiment (if available): {news_sentiment}

Now, apply advanced verification techniques used by elite traders (including Chinese proprietary firms) such as:
- Multi-timeframe confluence (M1, M5, M15, H1)
- Order flow imbalance and volume profile
- Candlestick pattern recognition (e.g., engulfing, pin bars, inside bars)
- Market microstructure signals (e.g., liquidity sweeps, stop hunts)
- Correlation with related pairs (e.g., EURUSD vs USDX)
- Expiry specific risks (Are we buying straight into a local resistance that will pin the 5-min candle?)
- Consideration of upcoming high-impact news events (if known)

Return a JSON object with the following fields:
- direction: string, exactly one of ["UP", "DOWN"] (your predicted direction for the next candle)
- confidence: integer 0-100 (how sure you are of your verdict)
- reasoning: string (brief explanation of your analysis)
"""
    
    try:
        response = _model.generate_content(prompt)
        text = response.text.strip()
        
        parsed = json.loads(text)
        
        direction_pred = parsed.get("direction", "UNKNOWN").upper()
        reason = parsed.get("reasoning", "No reasoning provided.")
        gemini_conf = parsed.get("confidence", 0)
        
        return {
            "approved": True,  # Always pass through now
            "reason": f"Gemini Predicts {direction_pred} ({gemini_conf}%): {reason}",
            "gemini_confidence": gemini_conf,
            "verdict": direction_pred
        }
            
    except Exception as e:
        log.warning("Gemini API call failed for %s: %s", symbol, e)
        # Fail open by defaulting to original direction if API goes down
        return {"approved": True, "reason": f"Gemini Error (Auto-Passed): {str(e)}", "gemini_confidence": 0, "verdict": direction}
